// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6c8da71e-84e4--abfa-9f8f91df87a1";

const char SSID[]               = "";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "";    // Secret device password

void onManualCleaningChange();
void onManualRefillChange();

String status;
float refillLevel;
float wasteLevel;
bool manualCleaning;
bool manualRefill;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(refillLevel, READ, ON_CHANGE, NULL, 5);
  ArduinoCloud.addProperty(wasteLevel, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(manualCleaning, READWRITE, ON_CHANGE, onManualCleaningChange);
  ArduinoCloud.addProperty(manualRefill, READWRITE, ON_CHANGE, onManualRefillChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
